name: Rust

on:
  pull_request:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Prepare
      run: make prepare
    - name: Build WASM
      run: cd crates/ckb-fixed && make wasm-pack
    - name: Clippy & Format
      run: cargo clippy && cargo fmt -- --check
    - name: Build Example
      run: make build
    - name: Tests
      run: cargo test

